version: '3'
services:

#mssql docker
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
    networks:
      - skicentarnet

  skicentar-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - skicentarnet

  mailing-service:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.emailsender
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VIRTUALHOST=/
      - EMAIL_APIKEY=nejma
      - EMAIL_SENDER=david.dautbegovic@edu.fit.ba
    depends_on:
      - rabbitmq
      - skicentar-sql
      - skicentar-api
    networks:
      - skicentarnet
    ports:
      - 7101:80

  skicentar-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=skicentar-sql,1433;Database=skicentar2024;User=sa;Password=QWElkj132!;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 49153:49153
    networks:
      - skicentarnet
    links:
      - skicentar-sql
    depends_on:
      - skicentar-sql
      
networks:
  skicentarnet:
    driver: bridge      